import {
  park1,
  park10,
  park11,
  park12,
  park13,
  park2,
  park3,
  park4,
  park5,
  park6,
  park7,
  park8,
  park9,
} from '../../assets/images/listing-assets'

const listingItems = [
  {
    id: '8b7-406',
    title: 'driveway oasis',
    postedBy: 'Mhanlo Loco',
    location: 'valenzuela',
    parkType: 'home-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park1,
    features: ['Covered Parking', 'Gated', 'Free Car Wash'],
  },
  {
    id: 'a94-c94',
    title: 'park and relax haven',
    postedBy: 'Denise West',
    location: 'quezon',
    parkType: 'home-parking',
    carType: ['SUV'],
    distance: 100,
    ratings: 3,
    img: park2,
    features: ['Security Camera Coverage', 'Close to Public Transit'],
  },
  {
    id: 'cf7-64d',
    title: 'carport paradise',
    postedBy: 'Irene Douglas',
    location: 'taguig',
    parkType: 'home-parking',
    carType: ['SUV', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park3,
    features: ['Covered Parking', 'Gated', 'Free Car Wash'],
  },
  {
    id: 'b2-40f',
    title: 'garage haven',
    postedBy: 'Alicia Harvey',
    location: 'pasay',
    parkType: 'home-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park4,
    features: ['Covered Parking', 'Gated', 'Free Car Wash'],
  },
  {
    id: 'b51-b78',
    title: 'vehicle sanctuary',
    postedBy: 'Monica Gonzalez',
    location: 'manila',
    parkType: 'home-parking',
    carType: ['Sedan', 'SUV', 'Light Truck'],
    distance: 100,
    ratings: 3,
    img: park5,
    features: ['Covered Parking', 'Gated', 'Free Car Wash'],
  },
  {
    id: '0aa-914',
    title: 'parking paradise',
    postedBy: 'Christina Shelton',
    location: 'caloocan',
    parkType: 'home-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park6,
    features: [],
  },
  {
    id: '63f-360',
    title: 'driveway delight',
    postedBy: 'Becky Watson',
    location: 'mandaluyong',
    parkType: 'home-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park7,
    features: ['Covered Parking', 'Gated', 'Free Car Wash'],
  },
  {
    id: '1fe-5ee',
    title: 'garage retreat',
    postedBy: 'Gail Shelton',
    location: 'pasig',
    parkType: 'home-parking',
    carType: ['Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park8,
    features: ['Covered Parking', 'Gated', 'Free Car Wash'],
  },
  {
    id: 'e85-0ba',
    title: 'restful retreat',
    postedBy: 'Joan Martinez',
    location: 'valenzuela',
    parkType: 'establishment-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park9,
    features: ['Covered Parking', 'Gated', 'Free Car Wash'],
  },
  {
    id: '8b8-2f5',
    title: 'safe spot sanctuary',
    postedBy: 'Ethan Collins',
    location: 'manila',
    parkType: 'establishment-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park10,
    features: ['Covered Parking', 'Gated', 'Free Car Wash'],
  },
  {
    id: '34a-e81',
    title: 'Car Haven Hub',
    postedBy: 'Arlene Hopkins',
    location: 'makati',
    parkType: 'establishment-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park11,
    features: ['Covered Parking', 'Gated', 'Free Car Wash'],
  },
  {
    id: '0a-a45',
    title: 'parking nest',
    postedBy: 'Dale Chapman',
    location: 'las piñas',
    parkType: 'establishment-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park12,
    features: ['Covered Parking', 'Gated', 'Free Car Wash'],
  },
  {
    id: '846-f4b',
    title: 'auto sanctuary',
    postedBy: 'Manuel James',
    location: 'manila',
    parkType: 'parking-Lot',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park13,
    features: ['Covered Parking', 'Gated', 'Free Car Wash'],
  },
]

export default listingItems
