import { park1, park10, park11, park12, park13, park2, park3, park4, park5, park6, park7, park8, park9 } from '../../assets/images/listing-assets'

const listingItems = [
  {
    id: '8b7-406',
    location: 'valenzuela',
    parkType: 'home-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park1,
  },
  {
    id: 'a94-c94',
    location: 'quezon',
    parkType: 'home-parking',
    carType: 'SUV',
    distance: 100,
    ratings: 3,
    img: park2,
  },
  {
    id: 'cf7-64d',
    location: 'taguig',
    parkType: 'home-parking',
    carType: ['SUV', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park3,
  },
  {
    id: 'b2-40f',
    location: 'pasay',
    parkType: 'home-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park4,
  },
  {
    id: 'b51-b78',
    location: 'manila',
    parkType: 'home-parking',
    carType: ['Sedan', 'SUV', 'Light Truck'],
    distance: 100,
    ratings: 3,
    img: park5,
  },
  {
    id: '0aa-914',
    location: 'caloocan',
    parkType: 'home-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park6,
  },
  {
    id: '63f-360',
    location: 'mandaluyong',
    parkType: 'home-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park7,
  },
  {
    id: '1fe-5ee',
    location: 'pasig',
    parkType: 'home-parking',
    carType: 'Motorcyle',
    distance: 100,
    ratings: 3,
    img: park8,
  },
  {
    id: 'e85-0ba',
    location: 'valenzuela',
    parkType: 'establishment-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park9,
  },
  {
    id: '8b8-2f5',
    location: 'manila',
    parkType: 'establishment-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park10,
  },
  {
    id: '34a-e81',
    location: 'makati',
    parkType: 'establishment-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park11,
  },
  {
    id: '0a-a45',
    location: 'las piñas',
    parkType: 'establishment-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park12,
  },
  {
    id: '846-f4b',
    location: 'manila',
    parkType: 'parking-Lot',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park13,
  },
]

export default listingItems
