import {
  park1,
  park10,
  park11,
  park12,
  park13,
  park2,
  park3,
  park4,
  park5,
  park6,
  park7,
  park8,
  park9,
} from '../../assets/images/listing-assets'

const listingItems = [
  {
    id: '8b7-406',
    title: 'driveway oasis',
    location: 'valenzuela',
    parkType: 'home-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park1,
  },
  {
    id: 'a94-c94',
    title: 'park and relax haven',
    location: 'quezon',
    parkType: 'home-parking',
    carType: 'SUV',
    distance: 100,
    ratings: 3,
    img: park2,
  },
  {
    id: 'cf7-64d',
    title: 'carport paradise',
    location: 'taguig',
    parkType: 'home-parking',
    carType: ['SUV', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park3,
  },
  {
    id: 'b2-40f',
    title: 'garage haven',
    location: 'pasay',
    parkType: 'home-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park4,
  },
  {
    id: 'b51-b78',
    title: 'vehicle sanctuary',
    location: 'manila',
    parkType: 'home-parking',
    carType: ['Sedan', 'SUV', 'Light Truck'],
    distance: 100,
    ratings: 3,
    img: park5,
  },
  {
    id: '0aa-914',
    title: 'parking paradise',
    location: 'caloocan',
    parkType: 'home-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park6,
  },
  {
    id: '63f-360',
    title: 'driveway delight',
    location: 'mandaluyong',
    parkType: 'home-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park7,
  },
  {
    id: '1fe-5ee',
    location: 'pasig',
    parkType: 'home-parking',
    carType: 'Motorcyle',
    distance: 100,
    ratings: 3,
    img: park8,
  },
  {
    id: 'e85-0ba',
    title: 'restful retreat',
    location: 'valenzuela',
    parkType: 'establishment-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park9,
  },
  {
    id: '8b8-2f5',
    title: 'safe spot sanctuary',
    location: 'manila',
    parkType: 'establishment-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park10,
  },
  {
    id: '34a-e81',
    title: 'Car Haven Hub',
    location: 'makati',
    parkType: 'establishment-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park11,
  },
  {
    id: '0a-a45',
    title: 'parking nest',
    location: 'las piñas',
    parkType: 'establishment-parking',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park12,
  },
  {
    id: '846-f4b',
    title: 'auto sanctuary',
    location: 'manila',
    parkType: 'parking-Lot',
    carType: ['SUV', 'Sedan', 'Motorcyle'],
    distance: 100,
    ratings: 3,
    img: park13,
  },
]

export default listingItems
